---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/sessions":
    post:
      summary: Creates an authenticated session
      tags:
      - Session
      operationId: authenticate
      parameters: []
      responses:
        '200':
          description: session authenticated
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/user_dto"
        '422':
          description: invalid request
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/error_dto"
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/phone_confirmation"
    get:
      summary: get session
      tags:
      - Session
      operationId: getCurrentSession
      responses:
        '200':
          description: session info
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/user_dto"
        '401':
          description: unauthorized
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/error_dto"
    delete:
      summary: Deletes an auth session
      tags:
      - Session
      operationId: logout
      responses:
        '200':
          description: session deleted
          content: {}
        '401':
          description: unauthorized
          content: {}
  "/users":
    post:
      summary: SMS confirmation for new/existing phone user
      tags:
      - User
      operationId: sendConfirmation
      parameters: []
      responses:
        '201':
          description: sms confirmation sent
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/register_dto"
        '422':
          description: invalid request
          content: {}
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/register_dto"
servers:
- url: https://{defaultHost}/api/v1
  variables:
    defaultHost:
      default: api.levimurray.dev
components:
  schemas:
    error_dto:
      type: object
      properties:
        message:
          type: string
    user_dto:
      type: object
      properties:
        id:
          type: string
        phone_number:
          type: string
        profile_status:
          "$ref": "#/components/schemas/profile_status"
      required:
      - id
      - phone_number
      - profile_status
    register_dto:
      type: object
      properties:
        phone_number:
          type: string
      required:
      - phone_number
    phone_confirmation:
      type: object
      properties:
        phone_number:
          type: string
        confirmation_pin:
          type: string
      required:
      - phone_number
      - confirmation_pin
    profile_status:
      type: string
      enum:
      - profile_status_name
      - profile_status_address
      - profile_status_billing
      - profile_status_complete
