/**
 * API V1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { BaseResponse } from './baseResponse';
import { BaseResponseError } from './baseResponseError';
import { CustomerDto } from './customerDto';
import { CustomerResponseAllOf } from './customerResponseAllOf';
import { StatusCode } from './statusCode';


export interface CustomerResponse { 
    status: StatusCode;
    error: BaseResponseError;
    data?: CustomerDto;
}

