/**
 * API V1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CustomerDto { 
    email: string;
    first_name: string;
    last_name: string;
    auth_provider?: string;
    auth_provider_uid: string;
    avatar_url?: string;
}

