/**
 * API V1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CustomerDto } from './customerDto';
import { AppPlatform } from './appPlatform';


export interface CustomerRegistration { 
    user_data: CustomerDto;
    auth_provider_token: string;
    app_platform: AppPlatform;
}

