/**
 * API V1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type LocationType = 'commercial' | 'residential';

export const LocationType = {
    Commercial: 'commercial' as LocationType,
    Residential: 'residential' as LocationType
};

