/**
 * API V1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type OrderType = 'commercial_pick_up' | 'private_pick_up';

export const OrderType = {
    CommercialPickUp: 'commercial_pick_up' as OrderType,
    PrivatePickUp: 'private_pick_up' as OrderType
};

