/**
 * API V1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type ProfileStatus = 'profile_status_name' | 'profile_status_address' | 'profile_status_billing' | 'profile_status_complete';

export const ProfileStatus = {
    Name: 'profile_status_name' as ProfileStatus,
    Address: 'profile_status_address' as ProfileStatus,
    Billing: 'profile_status_billing' as ProfileStatus,
    Complete: 'profile_status_complete' as ProfileStatus
};

