/**
 * API V1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Profile } from './profile';


export interface UserDto { 
    id: string;
    phone_number: string;
    profile: Profile;
    complete_profile: boolean;
    complete_name: boolean;
    complete_address: boolean;
    complete_billing?: boolean;
}

